title: FreshKeeper
description: FreshKeeper is a mobile app that helps users track their food’s expiration dates and minimize waste. By providing timely reminders and simplifying the process of managing food inventories, FreshKeeper encourages smarter consumption habits and reduces household food waste.
markdown: kramdown
theme: minima

header_pages:
  - terms-of-service.md
  - privacy-policy.md
  - imprint.md

locale: "de-DE"
lang: "de"
timezone: "Europe/Berlin"

plugins:
  - jekyll-seo-tag

minima:
  skin: classic
  custom_css:
    - /assets/css/custom.css
